### ISSUE TITLE
Incorrect MPP resolution handling from JP2 image

### ISSUE THREAD

**Issue by himekifee** [John-P/wsic#54]
- wsic version: v0.6.1
- Python version: 3.10
- Operating System: Ubuntu 20.04

### Description
By inspecting the jp2 metadata I see the `Capture X Resolution` is 36364 and the unit is cm. The corresponding MPP is 0.275
![图片](https://user-images.githubusercontent.com/65988663/207849481-e6e5fa83-4964-455f-85d0-202e6bb438b9.png)
However, In the code, the resolution box reads 3636400 and an MPP of approx. 0.00275.
![image2](https://user-images.githubusercontent.com/65988663/207848894-a351697e-bbbf-412c-8960-bfabcea7fbe0.png)
![image3](https://user-images.githubusercontent.com/65988663/207848905-5e262343-a34f-41cd-9075-822259db47a1.png)

### What I Did

```
wsic convert -i in.jp2 -o out.tiff -rt 4096 4096 -w 2 --no-ome --overwrite -to 180 -c jpeg -cl 95 -d 2 -d 4 -d 8
```

**Comment by John-P** [comment]
This should be fixed shortly in the line PR. Thank you for identifying this.
