### ISSUE TITLE
MPP data missing from OpenSlideReader

### ISSUE THREAD

**Issue by himekifee** [John-P/wsic#73]
- wsic version: 0.7
- Python version: 3.10.9
- Operating System: ArchLinux

### Description
When trying to create a pyramid TIFF image from a single-level tiff image, MPP got lost in the output TIFF file.

### What I Did

```
wsic convert -i in.tiff -o test_out.tiff -rt 4096 4096 -w 20 --no-ome --overwrite -to 180 -c jpeg -d 2 -d 4 -d 8
```
### Note
I debugged a bit and found out [this](https://github.com/John-P/wsic/blob/ff21d85eecb5c8371bfb717f563a62378efc4352/wsic/readers.py#L827) function call caused the error. Inside [ppu2mpp](https://github.com/John-P/wsic/blob/ff21d85eecb5c8371bfb717f563a62378efc4352/wsic/utils.py#L221) function, the actual unit passed was "centimeter" instead of "cm" according to openslide standard. After adding `"centimeter": 1e4,` to L238, the output got corrected.

**Comment by John-P** [comment]
This should be fixed but the linked PR now
